services:
  twitch-overlay:
    container_name: twitch-overlay
    build: .
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=${FLASK_DEBUG:-True}
      - FLASK_HOST=${FLASK_HOST:-0.0.0.0}
      - FLASK_PORT=${FLASK_PORT:-5000}

      - CLIENT_ID=${CLIENT_ID:-placeholder}
      - SECRET=${SECRET:-placeholder}
      - BROADCASTER_ID=${BROADCASTER_ID:-placeholder}
      
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN:-placeholder}
      - DOMINIO=${DOMINIO:-placeholder}
    ports:
      - "8080:${FLASK_PORT}"
    pull_policy: build

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "--domain=${DOMINIO:-placeholder}"
      - "twitch-overlay:${FLASK_PORT:-5000}"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN:-placeholder}
      - DOMINIO=${DOMINIO:-placeholder}
    ports:
      - 4040:4040
